In [ ]:
from google.colab import drive
drive.mount("/content/drive")


Mounted at /content/drive


In [ ]:
import pandas as pd
df=pd.read_csv("/content/drive/MyDrive/sample.jpg")

FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/MyDrive/sample.jpg'

In [ ]:
!pwd


/content


In [ ]:
!ls /content/drive/MyDrive/sample.jpg

/content/drive/MyDrive/sample.jpg


In [ ]:
import cv2
img = cv2.imread('sample.jpg')
print(img)

[[[132 111 120]
  [151 130 139]
  [167 146 155]
  ...
  [ 73 128 119]
  [ 80 137 129]
  [ 87 144 136]]

 [[ 99  78  87]
  [123 102 111]
  [144 123 132]
  ...
  [ 70 125 116]
  [ 86 143 134]
  [ 99 156 147]]

 [[ 83  65  72]
  [107  89  96]
  [130 109 117]
  ...
  [ 68 126 115]
  [ 86 144 133]
  [ 98 156 145]]

 ...

 [[ 71 105  88]
  [ 76 110  93]
  [ 91 124 109]
  ...
  [ 96 158 122]
  [ 93 157 121]
  [ 93 157 121]]

 [[ 69 100  85]
  [ 78 111  96]
  [ 95 128 114]
  ...
  [ 95 156 122]
  [ 92 156 121]
  [ 91 155 120]]

 [[ 70 101  86]
  [ 82 113  98]
  [ 94 127 113]
  ...
  [ 94 155 121]
  [ 90 154 119]
  [ 89 153 118]]]


In [ ]:
import numpy as np

kernel = np.ones((5, 5), np.float32) / 25  # 5x5 averaging filter
blurred_img = cv2.filter2D(img, -1, kernel)
print(blurred_img)


[[[126 106 114]
  [127 107 115]
  [133 112 121]
  ...
  [ 75 131 121]
  [ 79 136 126]
  [ 81 138 128]]

 [[127 106 115]
  [128 108 116]
  [134 113 121]
  ...
  [ 75 131 120]
  [ 78 135 124]
  [ 79 137 126]]

 [[126 107 114]
  [128 108 115]
  [133 113 121]
  ...
  [ 73 130 118]
  [ 75 133 121]
  [ 76 134 122]]

 ...

 [[ 81 115  99]
  [ 83 118 101]
  [ 88 123 107]
  ...
  [ 95 157 120]
  [ 94 157 120]
  [ 94 157 120]]

 [[ 82 115 100]
  [ 84 118 102]
  [ 89 124 109]
  ...
  [ 95 157 121]
  [ 94 156 121]
  [ 93 156 121]]

 [[ 82 115 100]
  [ 85 118 103]
  [ 90 124 109]
  ...
  [ 95 157 121]
  [ 94 156 121]
  [ 93 156 121]]]
